name: CI Workflow

on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: self-hosted  # Utiliser le runner self-hosté
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find and lint PHP files
        run: |
          for file in $(find . -name "*.php"); do
            php -l $file
          done


  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t nginx:latest -f /var/www/html/Dockerfile .


